package com.example.mobilevrlab.rest;

public enum Command {
    ACTIVATE_ATTENTION_MODE,
    DEACTIVATE_ATTENTION_MODE,
    ACTIVATE_TRANSPARENCY_MODE,
    DEACTIVATE_TRANSPARENCY_MODE,
    GET_STATUSES
}
